// Classic gaming-conference clichés to auto-fill a bingo board.
export const BINGO_TEMPLATES = [
  "A delay is announced",
  '"Our most ambitious game yet"',
  "A FromSoftware game appears",
  "Silksong finally gets a date",
  "A remaster nobody asked for",
  "Awkward on-stage banter",
  "A brand-new IP",
  "Standing ovation",
  "A Final Fantasy something",
  "Live-service game shown",
  "GTA 6 trailer (you wish)",
  "A celebrity cameo",
  '"Available right now!" shadow drop',
  "Sequel to a 10+ year-old game",
  'Someone says "community"',
  "Indie sizzle-reel montage",
  "Yet another soulslike",
  "Collector's edition shown",
  "Technical difficulties",
  "A Nintendo character cameo",
  "Cozy game with animals",
  "A roguelike",
  "Someone tears up on stage",
  "Surprise crossover/collab",
  "A battle royale",
  "Pre-order bonus mentioned",
  "Cinematic with zero gameplay",
  'Release date is "TBA 2027"',
  "A Like a Dragon / Yakuza game",
  "A metroidvania",
  '"PC port confirmed"',
  "Subscription service plug",
  "Pixel-art throwback",
  '"Passionate team"',
  "Hideo Kojima appears",
  "A horror game reveal",
  'Game with "2" in the title',
  "A dead franchise returns",
  "Day-one on Game Pass",
  "Trailer ends on a logo, no date",
  "Open world with a map icon overload",
  "Crowd cheers for a number",
];
